export const materials = [
  {
    value: 'pla',
    name: 'PLA',
    tag: 'Standard',
    color: 'rgba(255,255,255,0.12)',
    tg: '60°C',
    tensile: '~50 MPa',
    pricePerGram: 6,
    density: 1.24,
    wtMul: 1.0,
    best: 'Prototypes, display models, scale builds',
    desc: 'Best surface finish and detail of any FDM material. Not suited for high-heat or load-bearing applications.',
    avoid: 'Direct sunlight, hot car interiors',
  },
  {
    value: 'petg',
    name: 'PETG',
    tag: 'Functional',
    color: 'rgba(100,180,255,0.12)',
    tg: '80°C',
    tensile: '~50 MPa',
    pricePerGram: 12,
    density: 1.27,
    wtMul: 1.0,
    best: 'Enclosures, brackets, mechanical parts',
    desc: 'Good impact resistance with dimensional stability. Moisture-resistant and reliable for everyday functional parts.',
    avoid: 'High precision fits (tends to string)',
  },
  {
    value: 'asa',
    name: 'ASA',
    tag: 'Outdoor',
    color: 'rgba(100,220,130,0.12)',
    tg: '100°C',
    tensile: '~55 MPa',
    pricePerGram: 14,
    density: 1.07,
    wtMul: 1.00,
    best: 'Outdoor, automotive, signage',
    desc: 'UV and weather resistant. Keeps colour and structure under prolonged sun exposure. Similar to ABS but without the warping.',
    avoid: 'Fine detail work',
  },
  {
    value: 'tpu',
    name: 'TPU',
    tag: 'Flexible',
    color: 'rgba(255,200,80,0.12)',
    tg: '—',
    tensile: '~40 MPa / >400% elongation',
    pricePerGram: 14,
    density: 1.21,
    wtMul: 1.00,
    best: 'Gaskets, grips, seals, dampeners',
    desc: 'Rubber-like flexibility with high abrasion resistance. For parts that need to bend, compress, or absorb impact.',
    avoid: 'Rigid structural parts',
  },
  {
    value: 'pa6cf',
    name: 'PA6-CF',
    tag: 'High Strength',
    color: 'rgba(232,64,28,0.12)',
    tg: '185°C',
    tensile: '~110 MPa',
    pricePerGram: 20,
    density: 1.12,
    wtMul: 1.00,
    best: 'Structural parts, jigs, load-bearing',
    desc: 'Carbon fibre reinforced Nylon 6. Exceptional stiffness-to-weight ratio. The go-to for high-performance engineering builds.',
    avoid: 'Decorative parts (matte, industrial finish)',
  },
  {
    value: 'pa12cf',
    name: 'PA12-CF',
    tag: 'Industrial',
    color: 'rgba(180,100,255,0.12)',
    tg: '175°C',
    tensile: '~100 MPa',
    pricePerGram: 20,
    density: 1.08,
    wtMul: 1.00,
    best: 'Chemical exposure, aerospace, fixtures',
    desc: 'Carbon fibre reinforced Nylon 12. Better chemical resistance than PA6-CF. Suited for demanding industrial environments.',
    avoid: 'Budget-sensitive projects',
  },
  {
    value: 'lwpla',
    name: 'LW-PLA',
    tag: 'Lightweight',
    color: 'rgba(180,220,255,0.10)',
    tg: '60°C',
    tensile: '~20 MPa',
    pricePerGram: 8,
    density: 0.64,
    wtMul: 0.64,
    best: 'RC aircraft, drone frames, cosplay, light structural shells',
    desc: 'Foamed PLA that expands during printing — produces parts up to 40% lighter than standard PLA at the same volume. Ideal when weight is the primary constraint and loads are low.',
    avoid: 'Load-bearing or high-impact applications',
  },
  {
    value: 'petgcf',
    name: 'PETG-CF',
    tag: 'Reinforced',
    color: 'rgba(80,160,255,0.12)',
    tg: '85°C',
    tensile: '~70 MPa',
    pricePerGram: 16,
    density: 1.30,
    wtMul: 1.0,
    best: 'Functional enclosures, stiff brackets, camera mounts',
    desc: "Carbon fibre reinforced PETG — combines PETG's dimensional stability and moisture resistance with significantly higher stiffness. Great middle ground between PETG and full engineering nylons.",
    avoid: 'Fine cosmetic details (matte, fibrous finish)',
  },
  {
    value: 'asaaero',
    name: 'ASA Aero',
    tag: 'Aerospace',
    color: 'rgba(100,255,180,0.10)',
    tg: '105°C',
    tensile: '~60 MPa',
    pricePerGram: 18,
    density: 1.05,
    wtMul: 1.0,
    best: 'UAV bodies, outdoor signage, automotive trim, marine components',
    desc: 'High-performance ASA tuned for aeronautical and outdoor applications. Superior UV stability, low water absorption, and excellent layer adhesion make it the go-to for drone airframes and anything that lives outside permanently.',
    avoid: 'Indoor-only or budget-sensitive builds',
  },
  {
    value: 'custom',
    name: 'On Demand',
    tag: 'Custom',
    color: 'rgba(255,255,255,0.06)',
    tg: 'Varies',
    tensile: 'Varies',
    pricePerGram: null,
    density: null,
    wtMul: null,
    best: 'Specialty & composite requirements',
    desc: 'High-temp polymers and specialty filaments sourced on request. Tell us your application.',
    avoid: null,
  },
];

export const materialQuickPicker = [
  { q: 'Just a visual model or display piece?', a: 'PLA' },
  { q: 'Functional part indoors?', a: 'PETG' },
  { q: 'Goes outside or in a car?', a: 'ASA' },
  { q: 'Needs to flex or grip?', a: 'TPU' },
  { q: 'Load-bearing or high strength?', a: 'PA6-CF' },
  { q: 'Chemical exposure or aerospace?', a: 'PA12-CF' },
  { q: 'Weight is everything (RC/drone)?', a: 'LW-PLA' },
  { q: 'Stiff functional part with moisture resistance?', a: 'PETG-CF' },
  { q: 'Outdoor drone body or UV-critical part?', a: 'ASA Aero' },
  { q: 'Not sure?', a: 'Tell us the application — we advise free' },
];

export const infillPatterns = [
  { value: 'gyroid', label: 'Gyroid', desc: 'Best all-round strength & flexibility' },
  { value: 'grid', label: 'Grid', desc: 'Fast, strong, standard choice' },
  { value: 'honeycomb', label: 'Honeycomb', desc: 'Great lateral strength' },
  { value: 'cubic', label: 'Cubic', desc: 'Isotropic — equal strength all directions' },
  { value: 'lines', label: 'Lines', desc: 'Fastest print, lower strength' },
  { value: 'lightning', label: 'Lightning', desc: 'Minimal material, visual models only' },
  { value: 'concentric', label: 'Concentric', desc: 'Good for flexible parts (TPU)' },
  { value: 'unsure', label: "I'm not sure — advise me", desc: 'We will recommend based on your use case' },
];
